version: "3.9"

services:
  web:
    build:
      context: .
      args:
        DJANGO_PORT: ${DJANGO_PORT:-8001}
    command: gunicorn vizva.wsgi:application --bind 0.0.0.0:${DJANGO_PORT:-8001} --workers 3
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT:-8001}:${DJANGO_PORT:-8001}"
