"""
Django settings for vizva project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*$i%_^)@*k15*18_(@#8k#i@3_)ib_ueh5myt_f_3-#999v5$$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["vizva.jiffymenu.com"]

CSRF_TRUSTED_ORIGINS = [
    "https://vizva.jiffymenu.com",
    "http://vizva.jiffymenu.com"   # optional if you still allow HTTP
]



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vizva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vizva.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
from decouple import config
import dj_database_url

DATABASES = {
    "default": dj_database_url.parse(config("DATABASE_URL"))
}

default_db = DATABASES["default"]
if default_db["ENGINE"] == "django.db.backends.sqlite3":
    db_path = default_db["NAME"]
    if not os.path.exists(db_path):
        raise Exception(f"SQLite database file not found: {db_path}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


LOGIN_URL = '/login/'                   # Default login page
LOGIN_REDIRECT_URL = '/'                         # After login, redirect to home
LOGOUT_REDIRECT_URL = '/login/'         # After logout, redirect to login page
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Vizva Admin",
    "site_header": "Vizva Admin",
    "site_brand": "Vizva",
    "welcome_sign": "Welcome to Vizva Admin Dashboard",
    "copyright": "Vizva © 2025",

    # Sidebar and Navigation
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_sidebar_icons": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "app.notification": "fas fa-bell",
        "app.report": "fas fa-chart-line",
        "app.customer": "fas fa-user-tie",
    },

    # Top Menu Links (actions, external links, etc.)
    "topmenu_links": [
        {"name": "Dashboard", "url": "/admin", "permissions": ["auth.view_user"], "icon": "fas fa-home"},
        {"name": "Notifications", "url": "/admin/app/notification/", "icon": "fas fa-bell"},
        {"name": "Download", "url": "admin:export_all_models_xlsx", "icon": "fas fa-download"},
    ],

    # UI Customization
    "order_with_respect_to": ["auth", "app.customer", "app.notification", "app.report"],
    "search_model": "auth.User",

    # Themes & Colors
    "custom_css": "css/custom_admin.css",  # optional custom styling
    "custom_js": None,

    "show_ui_builder": True,  # Jazzmin’s live theme builder (great for tuning colors)
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-info",
    "navbar": "navbar-info navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

USE_TZ = True
TIME_ZONE = 'America/New_York'
