# Generated by Django 5.2.4 on 2025-08-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('status_flag', models.BooleanField(default=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app.expert')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume', models.URLField(help_text='Google Drive shareable link', unique=True)),
                ('status_flag', models.BooleanField(default=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='app.expert')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='app.technology')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('status_flag', models.BooleanField(default=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app.marketingteam')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Member',
                'verbose_name_plural': 'Marketing Team',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_technology', models.CharField(max_length=100)),
                ('candidate_email', models.EmailField(max_length=255)),
                ('candidate_resume', models.URLField(unique=True)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('feedback', models.TextField(blank=True)),
                ('JOB_DES', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('tag', 'Tag')], default='tag', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.candidate')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_filled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.company')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='app.expert')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.round')),
                ('support_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.supporttype')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='app.task')),
            ],
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_type', models.CharField(choices=[('INCENTIVIZED', 'Incentivized PO'), ('HONORABLE', 'Honorable PO')], default='INCENTIVIZED', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_entries', to='app.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_entries', to='app.company')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ph_entries', to='app.expert')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead_ph_entries', to='app.expert')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_entries', to='app.technology')),
            ],
            options={
                'verbose_name': 'PO Entry',
                'verbose_name_plural': 'PO Table',
            },
        ),
    ]
